### ISSUE TITLE
BSSID dublicates SSID at settings page

### ISSUE THREAD

**Issue by Phisik** [Jorgen-VikingGod/ESP8266-WiFi-Relay-Async#2]
**Settings.html** page #ssid list consist of items like:
```
<option value="my-wifi" bssidvalue="AA:BB:CC:DD:EE:FF">
  BSSID:AA:BB:CC:DD:EE:FF, Signal Strength: -61, Network: my-wifi
</option>
```
In **settings.js** we have @ lines 34-37
```
$('#ssid').change(function() {
  console.log('ssid changed');
  $('#wifiBSSID').val($('#ssid option:selected').val());
});
```
This fuctions returns selected value of  **#ssid** (= "my-wifi") and puts it in **#wifiBSSID**. As a result BSSID dublicates SSID, the data is saved to config.json, and **WiFi.begin(ssid, password, 0, bssid);** fails on boot. 

Since BSSID is stored at **bssidvalue** attribute you should change **settings.js** to 

```
$('#ssid').change(function() {
  console.log('ssid changed');
  $('#wifiBSSID').val(  $('#ssid option:selected').attr('bssidvalue')  );
});
```

**Comment by Jorgen-VikingGod** [comment]
thx for reporting - add the quick fix directly.
